### ISSUE TITLE
Write better README

### ISSUE THREAD

**Issue by Remeic** [Remeic/genesia#11]
Beautify this!
Use some screenshot and make simple logo

**Comment by hellotunmbi** [comment]
I made a pull request to this Issue. I wrote a better README for the project. Check it out 
https://github.com/Remeic/genesia/pull/15

**Comment by pkrc267** [comment]
> I made a pull request to this Issue. I wrote a better README for the project. Check it out
> #15

@hellotunmbi Good job! Much detailed README. (Might want to add the logo to beautify it. just in case)

**Comment by Remeic** [comment]
Hey guys! thanks for contributing, either PR was merged, thanks again!

@pkrc267 I don't see you logo, when i merge i see react logo and i remove some commit later.

It is my fault??

**Comment by pkrc267** [comment]
@Remeic I changed my initial logo(due to quality issue) and used react's logo that was already available (thought it to be much cool and gestured _made-with-react_). I understand that's not what you wanted :)

**Comment by DanteTheDevil** [comment]
> Beautify this!
> Use some screenshot and make simple logo



> Beautify this!
> Use some screenshot and make simple logo

Hello, friend. I also want to help you with better readmi, so check please my request. I have added an eye catching logo and rewritten all of its parts. I hope it will be usefull for you, good luck.
