### ISSUE TITLE
Use Hooks

### ISSUE THREAD

**Issue by Remeic** [Remeic/genesia#20]
Hooks everywhere, can implement the new trend on genesia?? Thanks

**Comment by adeelibr** [comment]
I am making a PR for this.
Change this file to Hooks only? https://github.com/Remeic/genesia/blob/master/src/Mail.js

Also should this be dumb functional component only https://github.com/Remeic/genesia/blob/master/src/App.js?

**Comment by Remeic** [comment]
@adeelibr hello! Thanks for contributing, I think you can implement hooks only in mail.js

**Comment by ccampean** [comment]
Mail.js is now rewrite using hooks, [#24](https://github.com/Remeic/genesia/pull/24)

**Comment by adeelibr** [comment]
@ccampean I was about to make a PR when i saw this :D Thank you for the heads up :)

**Comment by Remeic** [comment]
My proposal in #29 , what do you think? @adeelibr @ccampean

**Comment by ccampean** [comment]
I like the fact that the component is cleaner now.

**Comment by adeelibr** [comment]
@Remeic looks good to me.

**Comment by ccampean** [comment]
I missed that variable. It should be outside of state's component.

**Comment by Remeic** [comment]
@ccampean No problem, I'm here to learn. Thanks again!

**Comment by adeelibr** [comment]
I think it should inside the state component, because `getComposedMail` is used as a function in the state component that takes in 2 params, assuming there can be multiple `suffexes` for different components, I think it's better if it stays inside the component.

**Comment by Remeic** [comment]
@adeelibr so you advice to move suffix in the state of component, in case there are multiple suffixes, right?

**Comment by adeelibr** [comment]
Yes, & if you want more control over the `suffixes` just pass a `suffix` prop down your component, and have `defaultProp` for `suffix` = `somerandomvalue`  in case no one passes the `suffix` prop.

**Comment by Remeic** [comment]
@adeelibr Good advice! I consider to implement it on next PR, I can search more services like mailnesia
